### ISSUE TITLE
[BE] 리뷰별점 추가

### ISSUE THREAD

**Issue by kjklalala2** [Elice-SW-2-Team14/Animal-Hospital#185]
## 🔨 기능 설명
리뷰 별점 추가

## 📑 완료 조건
리뷰 별점 추가

## 💭 관련 백로그
[[BE] 내 병원 정보 페이지]-[API]-[]

## 💭 예상 작업 시간
1h

**Comment by WinterKwon** [comment]
리뷰api에 병원에 대한 별점 항목이 있는데 별도로 따로 만드시는 건가요?
