### ISSUE TITLE
[BE] 오류 핸들러 변경 적용 

### ISSUE THREAD

**Issue by kjklalala2** [Elice-SW-2-Team14/Animal-Hospital#254]
## 🔨 기능 설명
오류 핸들러 변경 적용  이후 안되어 있는 오류처리도 적용

## 📑 완료 조건
new Erro도 처리될 때

## 💭 관련 백로그
[백엔드]-[전체]

## 💭 예상 작업 시간
0.2h

**Comment by WinterKwon** [comment]
완료조건 관련해서 throw new Error가 필요한 부분도 있습니다. 모든 에러를 HttpError로 바꾸면 안될 것 같습니다
